import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import {ether, providers} from "ethers"
import web3Modal from "web3modal"

export default function Home() {
const [walletConnected,setWalletConnected] = useState(false);
const[ens, setENS] = useState("");
const[address, setAddress] =useState("");
const web3modalRef = useRef();

const setENSOrAddress = async (address, web3Provider) =>{
  const _ens = await web3Provider.lookupAddress(address);
  if (_ens){
   setENS(_ens);
  }
  else{
    setAddress(address);
  }
};

const getSignerOrProvider = async () => {
  const provider = await web3modalRef.current.connect();
  const web3Provider = new providers.Web3Provider(provider);
  const{chainId} = await web3Provider.getNetwork()
  if(chainId !== 4) {
   window.alert("change the network to rinkeby")
   throw new Error("change the network to rinkeby")
  }
  const signer = web3Provider.getSigner();
  const address = await signer.getAddress();
  await setENSOrAddress ( address,web3Provider);
  return signer;
}


const connectWallet = async () => {
  try {
    await getSignerOrProvider(true);
    setWalletConnected(true);
  } catch (error) {
    console.error("connectWallet",error);
  }
}

useEffect(() => {
  if(!walletConnected) {
    web3modalRef.current = new web3Modal({
      network:"rinkeby",
      providerOption:{},
      disableInjectedProvider:false
    });
    connectWallet();
  }

}, [walletConnected]);

 const renderButton = () =>{
  if (walletConnected) {
    <div>walletConnected</div>
  }
  else{
    return(
      <button onClick={connectWallet} className={styles.button}> connect your wallet </button>
    )
  };
 };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div>
          <h1 className={styles.title}> Welcome to learnWeb3 website  {ens? ens :address}! </h1>
        <div className={styles.description}> its an NFT collection for learnWeb3 punks.</div>
        {renderButton()}
        </div>
        <div> 
          <img className={styles.image} src="../Fox_1-removebg-preview.png" />
        </div>
      </div>
      
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
